# Generated by Django 6.0.1 on 2026-03-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_ids', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='domaintrafficevent',
            new_name='network_ids_domain_3183dd_idx',
            old_name='network_ids__domain__e4b123_idx',
        ),
        migrations.RenameIndex(
            model_name='domaintrafficevent',
            new_name='network_ids_domain_1f4ba7_idx',
            old_name='network_ids__domain__a3e7f5_idx',
        ),
    ]
