# Generated by Django 6.0.1 on 2026-02-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_mfa_enabled_customuser_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_backup_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
