# Generated by Django 6.0.1 on 2026-02-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('AES-256-GCM', 'AES-256-GCM'), ('RSA-2048', 'RSA-2048'), ('SHA-256', 'SHA-256'), ('SHA-512', 'SHA-512'), ('Base64', 'Base64')], max_length=20)),
                ('plaintext_preview', models.CharField(blank=True, max_length=100)),
                ('ciphertext', models.TextField()),
                ('key', models.TextField(blank=True, null=True)),
                ('nonce', models.TextField(blank=True, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('hash_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
