# Generated by Django 6.0.1 on 2026-02-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypteddata',
            name='plaintext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encrypteddata',
            name='algorithm',
            field=models.CharField(choices=[('AES-256-GCM', 'AES-256-GCM'), ('RSA-2048', 'RSA-2048'), ('MD5', 'MD5'), ('SHA-1', 'SHA-1'), ('SHA-256', 'SHA-256'), ('SHA-512', 'SHA-512'), ('Base64', 'Base64')], max_length=20),
        ),
        migrations.AlterField(
            model_name='encrypteddata',
            name='ciphertext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
