# Generated by Django 6.0.1 on 2026-03-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_customuser_mfa_backup_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhishingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(blank=True, default="", max_length=255)),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("preview", models.TextField(blank=True, default="")),
                ("full_body", models.TextField(blank=True, default="")),
                (
                    "score",
                    models.IntegerField(default=0, help_text="AI risk score 0-100"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("phishing", "Phishing"),
                            ("suspicious", "Suspicious"),
                            ("clean", "Clean"),
                        ],
                        default="clean",
                        max_length=20,
                    ),
                ),
                ("ai_label", models.CharField(blank=True, default="", max_length=50)),
                ("ai_reasons", models.JSONField(blank=True, default=list)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phishing_logs",
                        to="users.customuser",
                    ),
                ),
            ],
            options={
                "db_table": "phishing_logs",
                "ordering": ["-scanned_at"],
            },
        ),
    ]
