# Generated by Django 6.0.1 on 2026-03-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlacklistedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=45, unique=True)),
                ("reason", models.CharField(default="Manual block", max_length=255)),
                ("blocked_by", models.CharField(default="admin", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blacklisted IP",
                "verbose_name_plural": "Blacklisted IPs",
                "ordering": ["-created_at"],
            },
        ),
    ]
