# Generated by Django 6.0.1 on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlookaccount',
            name='_client_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlookaccount',
            name='_client_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlookaccount',
            name='auth_tenant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
